# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a37d1f99779d776113fd1e021949b606"
name = "promo-banner-app"
handle = "promo-banner-app-2"
application_url = "https://souls-liechtenstein-planes-gm.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://souls-liechtenstein-planes-gm.trycloudflare.com/auth/callback",
  "https://souls-liechtenstein-planes-gm.trycloudflare.com/auth/shopify/callback",
  "https://souls-liechtenstein-planes-gm.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
